# This is a rmd config.

title = "RMD Config"

[default]
address = "localhost"
policypath = "/usr/local/etc/rmd/policy.toml"
tlsport = 8443
# certpath = "/usr/local/etc/rmd/cert/server" # Only support pem format, hard code that CAFile is ca.pem, CertFile is rmd-cert.pem, KeyFile is rmd-key.pem
# clientcapath = "/usr/local/etc/rmd/cert/client" # Only support pem format, hard code that CAFile is ca.pem
clientauth = "no"  # can be "no, require, require_any, challenge_given, challenge", challenge means require and verify.
# unixsock = "/var/run/rmd.sock"

[log]
path = "/var/log/rmd/rmd.log"
env = "dev"  # production or dev
level = "debug"
stdout = true

[database]
backend = "bolt" # mgo
transport = "/var/run/rmd/rmd.db" # mongodb://localhost
dbname = "bolt"

[debug]
enabled = true
debugport = 8081

[OSGroup] # OSGroup is mandatory
cacheways = 1
cpuset = "0-1"

[InfraGroup] # InfraGroup is optional
cacheways = 10
cpuset = "2-3"
tasks = ["ovs*"] # Just support Wildcards. Do we need to support RE?

[CachePool] # Cache Pool config is optional
shrink = true
max_allowed_shared = 10 # max allowed workload in shared pool, default is 10
guarantee = 6
besteffort = 3
shared = 1

[acl]
path = "/usr/local/etc/rmd/acl/"  #
# use CSV format
filter = "url" # at present just support "url", will support "ip, proto"
authorization = "signature" # authorize the client, can identify client by signature, role(OU) or username(CN). Default value is signature. If value is signature, admincert and usercert should be set.
admincert = "/usr/local/etc/rmd/acl/roles/admin/" # A cert is used to describe user info. These cert files in this path are used to define the users that are admin. Only pem format file at present. The files can be updated dynamicly.
usercert = "/usr/local/etc/rmd/acl/roles/user/" # A cert is used to describe user info. These cert files in this path are used to define the user with low privilege. Only pem format file at present. The files can be updated dynamicly.

[pam]
service = "rmd"
